services:
  mongodb:
    image: mongo:7
    container_name: miketea-mongodb
    volumes:
      - miketea-mongodb-data:/data/db
    networks:
      - miketea-network
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miketea-backend
    env_file:
      - ./.env
    environment:
      MONGODB_URI: mongodb://mongodb:27017
    expose:
      - "3000"
    volumes:
      - /var/log/miketea-machine:/var/log/miketea-machine
    networks:
      - miketea-network
    restart: always
    depends_on:
      - mongodb

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    container_name: miketea-frontend
    ports:
      - "80:80"
    networks:
      - miketea-network
    restart: always
    depends_on:
      - backend

networks:
  miketea-network:
    driver: bridge

volumes:
  miketea-mongodb-data:
